- name: Copy Nginx Dockerfile and configuration
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/nginx/{{ item }}"
  with_items:
    - Dockerfile
    - nginxScript.sh
    - default.conf

- name: Build Nginx Docker image
  docker_image:
    build:
      path: "/home/{{ ansible_user }}/nginx"  
    name: nginx
    state: present
    source: build
    tag: 1337
