---
- name: Cloud1 - Deploy Inception Project Using Ansible
  hosts: cloud_machine
  become: yes     # privilege escalation
  roles:
    - common
    - docker
    - nginx
    - mariadb
    - wordpress
