---
- name: Cloud1 - Deploy Inception Project Using Ansible
  hosts: all
  become: yes
  vars_files:
    - secrets.yaml
  vars:
    ansible_host_key_checking: False
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - nginx
    - mariadb
    - wordpress
    - docker
