---
- name: Cloud1 - Deploy Inception Project Using Ansible
  hosts: cloud_machine
  become: yes     # privilege escalation
  remote_user: root
  roles:
    - common
    - nginx
    - mariadb
    - wordpress
    - docker
