version: '3.7'

networks:
  cloud1:
    name: cloud1
    driver: bridge

volumes:
  wordpress:
    name: wp_files
    driver_opts:
      device: "/home/newuser/data/mariadb"
      o: bind
      type: none
  mariadb:
    name: wp_database
    driver_opts:
      device: "/home/newuser/data/wordpress"
      o: bind
      type: none

services:
  mariadb:
    env_file: .env
    image: mariadb:1337
    container_name: mariadb
    networks:
      - cloud1
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  wordpress:
    env_file: .env
    image: wordpress:1337
    container_name: wordpress
    networks:
      - cloud1
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always


  nginx:
    env_file: .env
    image: nginx:1337
    container_name: nginx
    networks:
      - cloud1
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
