---
- name: Copy WordPress Dockerfile and configuration
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/wordpress/{{ item }}"
  with_items:
    - Dockerfile
    - script.sh


- name: Build WordPress Docker image
  docker_image:
    build:
      path: "/home/{{ ansible_user }}/wordpress"  
    name: wordpress
    state: present
    source: build
    tag: 1337

