---
# maybe we can copy and build in the /tmp folder
- name: Copy MariaDB Dockerfile and configuration files
  copy:
    src: "{{ item }}" # templated variable that gets its value from the loop items
    dest: "/home/{{ ansible_user }}/mariadb/{{ item }}"
  with_items:
    - Dockerfile
    - script.sh

- name: Build MariaDB Docker image
  docker_image:
    build:
      path: "/home/{{ ansible_user }}/mariadb"  
    name: mariadb
    tag: 1337
    state: present
    source: build