---
# common role to install dependencies
- name: Install necessary dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ca-certificates
    - curl
    - software-properties-common


- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add the Docker repository to Apt sources
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    update_cache: yes


- name: Install Docker and Docker Compose
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: create inception folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - nginx
    - wordpress
    - mariadb