- name: Ensure base project directory exists
  file:
    path: "/home/{{ ansible_user }}/Cloud_1"
    state: directory

- name: Ensure necessary volume directories exist for MariaDB and WordPress
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ansible_user}}/data/mariadb"
    - "/home/{{ansible_user}}/data/wordpress"

- name: Copy project configuration files
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/Cloud_1/{{ item }}"
  with_items:
    - docker-compose.yaml
    - .env

- name: Change domain name
  shell:
    sed -i 's/domain.42.fr/{{ ansible_host }}/g' "/home/{{ ansible_user }}/Cloud_1/.env"
    


- name: Deploy services with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/Cloud_1"
    build: always
    state: present

